### PR TITLE
Initial commmit to add basic logging via NLog.

### PR DESCRIPTION
**Pull request by crypt0m1nd3r**
I'll expand on this later (and add support for it in the 'neo' and 'neo-vm' repos too).  For now, I wanted to ensure that I can add the NLog dependency (I needed NLog v5 since .NET Core is not supported in v4, see: https://github.com/NLog/NLog).

The provided NLog.config file will only output Info-level messages (there are only 2 Debug-level messages right now in Program.cs).  Modify the 'minlevel' in NLog.config to be 'Debug' instead of 'Info' to see the log messages show up in the 'neo-cli.log' file (output in the CWD).

NOTE: the 'neo-cli' repo should probably also have a 'develop' branch (like the 'neo' repo does)...

### CODE REVIEW

**Comment by localhuman** [comment]
closed, the master branch of this repo tracks with the `neo-project/neo-cli` master. 
please make a pull request for the branch `feature-logging`.

Thanks!

**Comment by canesin** [comment]
Hi @localhuman, you can just click on "edit" and change the branch.. reopening with retarget.

**Comment by localhuman** [comment]
builds and runs on OSX and Linux.  Would it be possible to have the `minlevel` set to `Debug` for debug builds and `Info` for release builds?

**Comment by crypt0m1nd3r** [comment]
@localhuman -- just committed a change to do exactly that.  Thanks for the suggestion.

**Comment by localhuman** [comment]
@crypt0m1nd3r please make a PR of your branch to neo-project/neo-cli master

**Pull request merged**
